### PR TITLE
Support function for weight

### PR DESCRIPTION
**Pull request by fpohtmeh**
Related to #2

### CODE REVIEW

**Comment by DanWlker** [comment]
If we were to allow sorting by length of name, wouldn't it be better to expose a sorting function directly? 

I don't quite understand how this would be better and more extensible than weightage being a number. `weight` here is tied to each command, so we will have to consider the default value if it is not specified. Using a function for weight although provides more extensibility, also disallows us to provide a default `weight`. 

Ex. what should be the default value if we sort by length of name like you showed? 0 implies the name is empty, so any name that has a length will have a higher weight in all scenarios. How can we have a "negative" weight  so that it can be put at the other direction? and how would that fit in the context of length of name?

**Comment by fpohtmeh** [comment]
@DanWlker I will close this PR because I found some overcomplications. I'll describe a more sophisticated idea in the next message

**Comment by fpohtmeh** [comment]
@DanWlker 
My idea is the following: apply these changes to the config:
- Add a function `compare` to be used in the sorting
  - it accepts two commands as parameters
  - it returns true if the first command is less than the second after the sorting
  - it will be used in the `table.sort` as the 2nd parameter
- Remove `weight` from the command. With the new `compare` function, the user can add any property to the command and use it for sorting.

Examples:
```lua
opts = {
  commands = {
    --  
  },
  compare = function(cmd1, cmd2)
    return cmd1.name:upper() < cmd2.name::upper() -- this is the default implementation of the compare function
    -- Note that with the compare function, it's easy to sort in reverse order by using > instead of <
  end
}
```

```lua
local function last_used_datetime(cmd)
  -- save usage datetime in some dictionary `name => datetime`
  return last_usage_dict[cmd.name]
end

opts = {
  --
  compare = function(cmd1, cmd2)
    return last_used_datetime(cmd1) > last_used_datetime(cmd2) -- sort by last usage
  end
}
```

```lua
-- sort by category, then by name
opts = {
  compare = function(cmd1, cmd2)
     return cmd1.category < cmd2.category or cmd1.category == cmd2.category and cmd1.name < cmd2.name -- user may add as many custom properties as he wishes to each command. Also, he can handle unset values (nil) in the compare function
  end
}
```

This is more flexible way than the property `weight`

**Comment by DanWlker** [comment]
the sorting by last used is a good reason to implement this. But it should support different sorting based on the current tag as well.

If possible I would like to consider how weightage can fit into the picture, if not I will have to consider deprecating it.

Also sorting based on last used means it would have to sort every time toolbox is opened. I would like to think about whether there will be a slight delay when the list gets too large

So if there is a good interface, and a good enough justification for this we can proceed.

Please keep track in this https://github.com/DanWlker/toolbox.nvim/issues/9

**Comment by fpohtmeh** [comment]
The custom compare function will not affect the performance because sorting is a speedy operation.

Let me finish with #14 and then add more proof that the `compare` function is better than the `weight`

**Comment by DanWlker** [comment]
Alright looking forward to it, thank you!

**Pull request closed without merging**
